server:
  port: 8088
  servlet:
    context-path: /keva

spring:
  security:
    user:
      name: admin
      password: 1234
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:mysql://localhost:3306/human_manage
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: false
    driver-class-name: com.mysql.jdbc.Driver

springdoc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method